from tkinter import *
root = Tk()
root.geometry("950x500")
root['background']='#856ff8'
def choise():
    if(gender_value==1):
        root.configure()
    elif(gender_value==2):
        root.configure()
def choise1():
    if(course_value==1):
        root.configure()
    elif(course_value==2):
        root.configure()
    elif(course_value==3):
        root.configure()
    elif(course_value==4):
        root.configure()


Label(root, text="STUDENT REGISTRATION FORM",font="times 15 bold").grid(row=0,column=3)
fname_user=Label(root,text="FIRST NAME").grid(row=1,column=1)
lname_user=Label(root,text="LAST NAME").grid(row=2,column=1)
dob_user=Label(root,text="DATE OF BIRTH").grid(row=3,column=1)
email_user=Label(root,text="EMAIL ID").grid(row=4,column=1)
mobile_user=Label(root,text="MOBILE NUMBER").grid(row=5,column=1)
gender_user=Label(root,text="GENDER").grid(row=6,column=1)
address_user=Label(root,text="ADDRESS").grid(row=7,column=1)
city_user=Label(root,text="CITY").grid(row=8,column=1)
pin_user=Label(root,text="PIN CODE").grid(row=9,column=1)
state_user=Label(root,text="STATE").grid(row=10,column=1)
country_user=Label(root,text="COUNTRY").grid(row=11,column=1)
hobbies_user=Label(root,text="HOBBIES").grid(row=12,column=1)
qualify_user=Label(root,text="QUALIFICATION").grid(row=13,column=1)
board_user=Label(root,text="Board").grid(row=13,column=4)
percent_user=Label(root,text="Persentage").grid(row=13,column=5)
year_user=Label(root,text="Year of Passing").grid(row=13,column=6)
slno_user=Label(root,text="SL No").grid(row=13,column=2)
slno1_user=Label(root,text="1").grid(row=14,column=2)
slno2_user=Label(root,text="2").grid(row=15,column=2)
slno3_user=Label(root,text="3").grid(row=16,column=2)
slno4_user=Label(root,text="4").grid(row=17,column=2)
exam_user=Label(root,text="Examination").grid(row=13,column=3)
classx_user=Label(root,text="Class X").grid(row=14,column=3)
classxii_user=Label(root,text="Class XII").grid(row=15,column=3)
graduate_user=Label(root,text="Graduation").grid(row=16,column=3)
masters_user=Label(root,text="Masters").grid(row=17,column=3)
course_user=Label(root,text="COURSES APPLIED FOR").grid(row=18,column=1)

fname_value=StringVar()
lname_value=StringVar()
dob_value=IntVar()
email_value=StringVar()
mobile_value=IntVar()
address_value=StringVar()
city_value=StringVar()
pin_value=IntVar()
state_value=StringVar()
country_value=StringVar()
gender_value=IntVar()
hobbies_value=IntVar()
board_value=StringVar()
percent_value=StringVar()
year_value=StringVar()
course_value=IntVar()

fname_box=Entry(root,textvariable=fname_value).grid(row=1,column=2)
lname_box=Entry(root,textvariable=lname_value).grid(row=2,column=2)
email_box=Entry(root,textvariable=email_value).grid(row=4,column=2)
dob_box=Entry(root,textvariable=dob_value).grid(row=3,column=2)
mobile_box=Entry(root,textvariable=mobile_value).grid(row=5,column=2)
address_box=Entry(root,textvariable=address_value).grid(row=7,column=2)
city_box=Entry(root,textvariable=city_value).grid(row=8,column=2)
pin_box=Entry(root,textvariable=pin_value).grid(row=9,column=2)
state_box=Entry(root,textvariable=state_value).grid(row=10,column=2)
country_box=Entry(root,textvariable=country_value).grid(row=11,column=2)
rb1_box=Radiobutton(root,text="Male",variable=gender_value,value=1,command=choise).grid(row=6,column=2)
rb2_box=Radiobutton(root,text="Female",variable=gender_value,value=2,command=choise).grid(row=6,column=3)
cb1_box=Checkbutton(root,text="Drawing",variable=hobbies_value,).grid(row=12,column=2)
cb2_box=Checkbutton(root,text="Dancing",variable=hobbies_value).grid(row=12,column=3)
cb3_box=Checkbutton(root,text="Sketching",variable=hobbies_value).grid(row=12,column=4)
cb4_box=Checkbutton(root,text="Others",variable=hobbies_value).grid(row=12,column=5)
others_box=Entry(root,textvariable=hobbies_value).grid(row=12,column=6)
board1_box=Entry(root,textvariable=board_value).grid(row=14,column=4)
board2_box=Entry(root,textvariable=board_value).grid(row=15,column=4)
board3_box=Entry(root,textvariable=board_value).grid(row=16,column=4)
board4_box=Entry(root,textvariable=board_value).grid(row=17,column=4)
parcent1_box=Entry(root,textvariable=percent_value).grid(row=14,column=5)
parcent2_box=Entry(root,textvariable=percent_value).grid(row=15,column=5)
parcent3_box=Entry(root,textvariable=percent_value).grid(row=16,column=5)
parcent4_box=Entry(root,textvariable=percent_value).grid(row=17,column=5)
year1_box=Entry(root,textvariable=year_value).grid(row=14,column=6)
year2_box=Entry(root,textvariable=year_value).grid(row=15,column=6)
year3_box=Entry(root,textvariable=year_value).grid(row=16,column=6)
year4_box=Entry(root,textvariable=year_value).grid(row=17,column=6)

rb3_box=Radiobutton(root,text="BCA",variable=course_value,value=1,command=choise1).grid(row=18,column=2)
rb4_box=Radiobutton(root,text="B.com",variable=course_value,value=2,command=choise1).grid(row=18,column=3)
rb5_box=Radiobutton(root,text="B.Sc",variable=course_value,value=3,command=choise1).grid(row=18,column=4)
rb6_box=Radiobutton(root,text="B.A",variable=course_value,value=4,command=choise1).grid(row=18,column=5)

Button(text="Submit",command=root.destroy).grid(row=19,column=4)
Button(text="Reset",command=root.destroy).grid(row=19,column=5)

root.mainloop() 